OpenMP: support for uses_allocators clause: Fix build and test case regressions
Fix-up for commit 7a8f98b48104ccf10c6dceccc51b70de69288eaa
"OpenMP: support for uses_allocators clause".

As was already pointed out, 'libgomp/config.h.in' was not regenerated.

In a configuration with:

    checking whether the target supports __sync_*_compare_and_swap... (cached) no

..., I see:

    configure: error: offload hosts require __sync_val_compare_and_swap to build libgomp.
    make[1]: *** [Makefile:17208: configure-target-libgomp] Error 1

Fixed the inverted condition.

Next, I see:

    ../../../source-gcc/libgomp/config/linux/../../allocator.c: In function ‘omp_init_allocator’:
    ../../../source-gcc/libgomp/config/linux/../../allocator.c:619:28: error: passing argument 1 of ‘gomp_mutex_init’ makes pointer from integer without a cast [-Wint-conversion]
      619 |       gomp_mutex_init (data->lock);
          |                        ~~~~^~~~~~
          |                            |
          |                            gomp_mutex_t {aka int}
    ../../../source-gcc/libgomp/config/linux/../../allocator.c:619:28: note: possible fix: take the address with ‘&’
      619 |       gomp_mutex_init (data->lock);
          |                        ~~~~^~~~~~
          |                        &
    In file included from ../../../source-gcc/libgomp/libgomp.h:209,
                     from ../../../source-gcc/libgomp/config/linux/allocator.c:31:
    ../../../source-gcc/libgomp/config/linux/mutex.h:41:32: note: expected ‘gomp_mutex_t *’ {aka ‘int *’} but argument is of type ‘gomp_mutex_t’ {aka ‘int’}
       41 | gomp_mutex_init (gomp_mutex_t *mutex)
          |                  ~~~~~~~~~~~~~~^~~~~
    ../../../source-gcc/libgomp/config/linux/../../allocator.c: In function ‘gomp_map_omp_init_allocator’:
    ../../../source-gcc/libgomp/config/linux/../../allocator.c:1587:68: error: passing argument 1 of ‘gomp_mutex_init’ makes pointer from integer without a cast [-Wint-conversion]
     1587 |             (((struct omp_allocator_data *) allocator_data_devaddr)->lock);
          |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
          |                                                                    |
          |                                                                    gomp_mutex_t {aka int}
    ../../../source-gcc/libgomp/config/linux/../../allocator.c:1587:68: note: possible fix: take the address with ‘&’
     1587 |             (((struct omp_allocator_data *) allocator_data_devaddr)->lock);
          |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
          |              &
    ../../../source-gcc/libgomp/config/linux/mutex.h:41:32: note: expected ‘gomp_mutex_t *’ {aka ‘int *’} but argument is of type ‘gomp_mutex_t’ {aka ‘int’}
       41 | gomp_mutex_init (gomp_mutex_t *mutex)
          |                  ~~~~~~~~~~~~~~^~~~~
    make[4]: *** [Makefile:819: allocator.lo] Error 1

Fixed.

Testing (with as well as without 'HAVE_SYNC_BUILTINS'):

I see:

    PASS: g++.dg/gomp/deprecate-2.C  -std=c++20  at line 31 (test for warnings, line 22)
    PASS: g++.dg/gomp/deprecate-2.C  -std=c++20  at line 43 (test for warnings, line 34)
    PASS: g++.dg/gomp/deprecate-2.C  -std=c++20  expected multiline pattern lines 24-27
    PASS: g++.dg/gomp/deprecate-2.C  -std=c++20  expected multiline pattern lines 36-39
    [-XFAIL:-]{+XPASS:+} g++.dg/gomp/deprecate-2.C  -std=c++20 (test for excess errors)
    [Etc.]

..., due to:

    { dg-excess-errors "sorry, unimplemented: 'uses_allocators' clause" }

Removed.

I see:

    {+PASS: libgomp.c++/../libgomp.c-c++-common/uses_allocators-2.c  (test for errors, line 9)+}
    {+FAIL: libgomp.c++/../libgomp.c-c++-common/uses_allocators-2.c (test for excess errors)+}

..., due to:

    [...]/libgomp.c++/../libgomp.c-c++-common/uses_allocators-2.c:7:34: error: invalid conversion from 'int' to 'omp_alloctrait_key_t' [-fpermissive]
    [...]/libgomp.c++/../libgomp.c-c++-common/uses_allocators-2.c:16:40: error: invalid conversion from 'int' to 'omp_alloctrait_key_t' [-fpermissive]

Replaced '1' by 'omp_atk_sync_hint'.

I see:

    {+FAIL: libgomp.c++/../libgomp.c-c++-common/uses_allocators-9.c (test for excess errors)+}
    {+UNRESOLVED: libgomp.c++/../libgomp.c-c++-common/uses_allocators-9.c compilation failed to produce executable+}

..., due to:

    [...]/libgomp.c++/../libgomp.c-c++-common/uses_allocators-9.c:11:24: error: invalid conversion from 'void*' to 'int*' [-fpermissive]
    [...]/libgomp.c++/../libgomp.c-c++-common/uses_allocators-9.c:21:24: error: invalid conversion from 'void*' to 'int*' [-fpermissive]
    [...]/libgomp.c++/../libgomp.c-c++-common/uses_allocators-9.c:33:32: error: invalid conversion from 'void*' to 'int*' [-fpermissive]

Added type casts.

I see:

    [-PASS:-]{+FAIL:+} libgomp.fortran/dep-uses-allocators.f90   -O   at line 12 (test for warnings, line 11)
    PASS: libgomp.fortran/dep-uses-allocators.f90   -O   at line 2 (test for warnings, line 11)
    PASS: libgomp.fortran/dep-uses-allocators.f90   -O  (test for excess errors)

..., due to:

    { dg-message "sorry, unimplemented: 'uses_allocators' clause [...]

Removed.

I see:

    PASS: libgomp.fortran/uses_allocators-7.f90   -O  (test for excess errors)
    {+PASS: libgomp.fortran/uses_allocators-7.f90   -O  execution test+}
    {+PASS: libgomp.fortran/uses_allocators-7.f90   -O   scan-tree-dump-times gimple "#pragma omp target .*uses_allocators\\(memspace\\(\\), traits\\(trait\\) : my_alloc\\)" 1+}
    {+PASS: libgomp.fortran/uses_allocators-7.f90   -O   scan-tree-dump-times gimple "#pragma omp target .*uses_allocators\\(memspace\\(\\), traits\\(\\) : my_alloc\\)" 1+}
    {+FAIL: libgomp.fortran/uses_allocators-7.f90   -O   scan-tree-dump-times original "#pragma omp target .*uses_allocators\\(memspace\\(1\\), traits\\(\\) : my4\\) uses_allocators\\(memspace\\(\\), traits\\(t2\\) : my3\\) uses_allocators\\(memspace\\(\\), traits\\(\\) : my2\\) uses_allocators\\(memspace\\(3\\), traits\\(t\\) : my\\)" 1+}

XFAILed (for now.)

	gcc/testsuite/
	* g++.dg/gomp/deprecate-2.C: Remove obsolete 'dg-excess-errors'.
	libgomp/
	* config.h.in: Regenerate.
	* configure.ac [x$libgomp_cv_have_sync_builtins = xno]: Fix check.
	* configure: Regenerate.
	* allocator.c (omp_init_allocator, gomp_map_omp_init_allocator)
	[!HAVE_SYNC_BUILTINS]: Fix build.
	* testsuite/libgomp.c-c++-common/uses_allocators-2.c: Fix for C++ testing.
	* testsuite/libgomp.c-c++-common/uses_allocators-9.c: Likewise.
	* testsuite/libgomp.fortran/dep-uses-allocators.f90: Remove
	obsolete "sorry, unimplemented: [...]" diagnostic check.
	* testsuite/libgomp.fortran/uses_allocators-7.f90: XFAIL one
	'scan-tree-dump-times' check.

(cherry picked from commit 803dfda7bed667c1993430138eab1c264b7d9528)