c++: Diagnose return from [[noreturn]] function during constant evaluation [PR126354]
This PR complains about g++ not diagnosing return from [[noreturn]]
function (which is UB) during constant evaluation.

This patch diagnoses that.
I haven't included the [[noreturn]] function name in the diagnostics
as it is printed in the context:
/home/jakub/src/gcc/gcc/testsuite/g++.dg/cpp1y/pr126354.C:18:24:   in 'constexpr' expansion of 'bar()'
/home/jakub/src/gcc/gcc/testsuite/g++.dg/cpp1y/pr126354.C:15:7:   in 'constexpr' expansion of 'foo(false)'
/home/jakub/src/gcc/gcc/testsuite/g++.dg/cpp1y/pr126354.C:15:7: error: '[[noreturn]]' call returns
But if you think it is better to emit
error ("%<[[noreturn]]%> %qD call returns", fun);
instead, I can certainly do that.

2026-07-23  Jakub Jelinek  <jakub@redhat.com>

	PR c++/126354
	* constexpr.cc (cxx_eval_call_expression): Diagnose return from
	[[noreturn]] function.

	* g++.dg/cpp1y/pr126354.C: New test.
	* g++.dg/cpp26/pr126354.C: New test.

Reviewed-by: Jason Merrill <jason@redhat.com>