OpenMP: support for uses_allocators clause: Fix libgomp build for PTX < 4.1
Fix-up for commit 7a8f98b48104ccf10c6dceccc51b70de69288eaa
"OpenMP: support for uses_allocators clause", which regressed libgomp build for
PTX < 4.1 configurations:

    In file included from [...]/libgomp/config/nvptx/allocator.c:48:
    [...]/libgomp/config/nvptx/allocator.c:47:28: error: ‘__nvptx_lowlat_realloc’ defined but not used [-Werror=unused-function]
       47 | #define BASIC_ALLOC_PREFIX __nvptx_lowlat
          |                            ^~~~~~~~~~~~~~
    [...]/libgomp/config/nvptx/../../basic-allocator.c:63:27: note: in definition of macro ‘fn1’
       63 | #define fn1(prefix, name) prefix ## _ ## name
          |                           ^~~~~~
    [...]/libgomp/config/nvptx/../../basic-allocator.c:69:29: note: in expansion of macro ‘fn’
       69 | #define basic_alloc_realloc fn(BASIC_ALLOC_PREFIX,realloc)
          |                             ^~
    [...]/libgomp/config/nvptx/../../basic-allocator.c:69:32: note: in expansion of macro ‘BASIC_ALLOC_PREFIX’
       69 | #define basic_alloc_realloc fn(BASIC_ALLOC_PREFIX,realloc)
          |                                ^~~~~~~~~~~~~~~~~~
    [...]/libgomp/config/nvptx/../../basic-allocator.c:257:1: note: in expansion of macro ‘basic_alloc_realloc’
      257 | basic_alloc_realloc (char *heap, void *addr, size_t oldsize,
          | ^~~~~~~~~~~~~~~~~~~
    [...]/libgomp/config/nvptx/allocator.c:47:28: error: ‘__nvptx_lowlat_calloc’ defined but not used [-Werror=unused-function]
       47 | #define BASIC_ALLOC_PREFIX __nvptx_lowlat
          |                            ^~~~~~~~~~~~~~
    [...]/libgomp/config/nvptx/../../basic-allocator.c:63:27: note: in definition of macro ‘fn1’
       63 | #define fn1(prefix, name) prefix ## _ ## name
          |                           ^~~~~~
    [...]/libgomp/config/nvptx/../../basic-allocator.c:67:28: note: in expansion of macro ‘fn’
       67 | #define basic_alloc_calloc fn(BASIC_ALLOC_PREFIX,calloc)
          |                            ^~
    [...]/libgomp/config/nvptx/../../basic-allocator.c:67:31: note: in expansion of macro ‘BASIC_ALLOC_PREFIX’
       67 | #define basic_alloc_calloc fn(BASIC_ALLOC_PREFIX,calloc)
          |                               ^~~~~~~~~~~~~~~~~~
    [...]/libgomp/config/nvptx/../../basic-allocator.c:167:1: note: in expansion of macro ‘basic_alloc_calloc’
      167 | basic_alloc_calloc (char *heap, size_t size)
          | ^~~~~~~~~~~~~~~~~~
    cc1: all warnings being treated as errors
    make[7]: *** [Makefile:819: allocator.lo] Error 1

If, for PTX < 4.1, we're not proving OpenMP low-latency memory, just disable
the whole '__nvptx_lowlat_pool' machinery.

	libgomp/
	* config/nvptx/allocator.c [PTX < 4.1]: Fix build.
	* config/nvptx/team.c [PTX < 4.1]: Disable the whole
	'__nvptx_lowlat_pool' machinery.

(cherry picked from commit 675abe8b1494048a643b3f229499a5a7cbfb466d)